### ISSUE TITLE
Azure Key Vault secrets are not supported for `checkout` and `git` steps

### ISSUE THREAD

**Issue by madbrenner** [jenkinsci/azure-keyvault-plugin#93] opened 2021-10-11 15:49 UTC
### Dependencies

[Git plugin](https://plugins.jenkins.io/git/)
[Pipeline: SCM plugin](https://plugins.jenkins.io/workflow-scm-step/)
### Feature Request

I have recently been trying to move some credentials from our Jenkins Credential Vault over to a Key Vault, and one credential I am attempting to move is a GitHub PAT. It works for cases where we try to make use of the credential via a `withCredentials` step, however when attempting to use the Key Vault secret with the `git` step (provided by Git plugin), or `checkout` step (provided by Pipeline: SCM plugin), these calls fail. e.g:
```
10:58:31  [Pipeline] git
10:58:31  The recommended git tool is: NONE
10:58:31  using credential ****
10:58:31  Cloning the remote Git repository
10:58:31  Cloning repository ****
10:58:31   > git init **** # timeout=10
10:58:31  Fetching upstream changes from ****
10:58:31   > git --version # timeout=10
10:58:31   > git --version # 'git version 2.17.1'
10:58:31  using GIT_ASKPASS to set credentials ****
...
10:58:36  java.lang.NullPointerException
10:58:36  	at com.microsoft.azure.util.AzureCredentials.getSystemCredentialById(AzureCredentials.java:525)
10:58:36  	at com.microsoft.jenkins.keyvault.SecretClientCache.createClient(SecretClientCache.java:44)
10:58:36  	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141)
10:58:36  	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2413)
10:58:36  	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
10:58:36  	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2411)
10:58:36  	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2394)
10:58:36  	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
10:58:36  	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
10:58:36  	at com.microsoft.jenkins.keyvault.SecretClientCache.get(SecretClientCache.java:27)
10:58:36  	at com.microsoft.jenkins.keyvault.BaseSecretCredentials$SecretGetter.lambda$static$0(BaseSecretCredentials.java:78)
10:58:36  	at com.microsoft.jenkins.keyvault.BaseSecretCredentials.getKeyVaultSecret(BaseSecretCredentials.java:60)
10:58:36  	at org.jenkinsci.plugins.azurekeyvaultplugin.AzureKeyVaultUsernamePasswordCredentials.getPassword(AzureKeyVaultUsernamePasswordCredentials.java:35)
10:58:36  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.createPasswordFile(CliGitAPIImpl.java:2415)
10:58:36  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2060)
10:58:36  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:86)
10:58:36  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:624)
10:58:36  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:853)
10:58:36  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:160)
10:58:36  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:153)
10:58:36  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
10:58:36  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
10:58:36  	at hudson.remoting.Request$2.run(Request.java:376)
10:58:36  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
10:58:36  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:58:36  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:58:36  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:58:36  	at java.lang.Thread.run(Thread.java:748)
```

If this is not the correct location for this request please let me know, I realize it might be up to the Git or Pipeline: SCM plugins to implement some sort of support for this, but I figured this would be the place to start investigating to see if this might be possible.
Thank you!

**Comment by timja** [comment] 2021-10-11 19:59
Thinking on it, this will be the same as https://github.com/jenkinsci/azure-keyvault-plugin/issues/73

The null item is the system credential provider

Duplicate of https://github.com/jenkinsci/azure-keyvault-plugin/issues/73

**Closed by timja** 2021-10-11 19:59 UTC
